server:
  port: 8081

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviesdb
    username: root
    password: Luckystar521

  redis:
    database: 0
    host: localhost
    port: 6379
    password: "" # 如果没有密码，可以留空

mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: org.example.practice.entity


mail:
  host: smtp.163.com
  port: 25
  username: yujiajia969@163.com
  password: YNJLEBGSVHLCOTOB
  fromAddress: yujiajia969@163.com
  protocol: smtp
  default-encoding: UTF-8
  properties:
    mail:
      smtp:
        auth: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true


logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
